name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'
    
    - name: Setup pandoc
      uses: r-lib/actions/setup-pandoc@v2
    
    - name: Install R dependencies
      run: |
        install.packages(c('bookdown', 'knitr', 'rmarkdown', 'data.table', 'ggplot2', 'checkmate'))
      shell: Rscript {0}
    
    - name: Build documentation
      run: |
        cd docs
        Rscript build_documentation.R
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation
        # cname: your-custom-domain.com  # Optional: remove if not using custom domain