name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-docs.yml'
  workflow_dispatch:

permissions:
  contents: write  # Allow writing to repository (needed for gh-pages branch)
  pages: write    # Allow GitHub Pages deployment
  id-token: write # Allow OIDC token for deployment

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.0'
        use-public-rspm: true  # Use RStudio Package Manager for faster binary installs
    
    - name: Setup pandoc
      uses: r-lib/actions/setup-pandoc@v2
    
    - name: Install R dependencies with caching
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        working-directory: ./docs
        cache-version: 2  # Increment this to clear cache if needed
    
    - name: Build documentation
      run: |
        cd docs
        Rscript build_documentation.R
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation
        # cname: your-custom-domain.com  # Optional: remove if not using custom domain